[tool.poetry]
name = "problem4"
version = "0.1.0"
description = "solver for the bucket puzzle"
authors = ["diohabara <diohabara@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
